### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by AcidRaZor** [yooouuri/bulma-vue#4]
Is this in active development or feature complete for those looking to upgrade their vue 2 apps to vue 3 who is stuck with Buefy?

**Comment by jrcii** [comment]
*crickets*

**Comment by rogeriotaques** [comment]
Shoot! 
I just found this and was hoping for it to be in active maintenance, but am afraid it's not.

**Comment by rcoundon** [comment]
This could be helpful and is active - https://github.com/ntohq/buefy-next
